# Generated by Django 4.2.17 on 2024-12-21 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
